name: Test Release
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: "Job - ${{ matrix.name }}"
    runs-on: "${{ matrix.os }}"
    env:
      CI_JOB_NAME: "${{ matrix.name }}"
    strategy:
      matrix:
        include:
          - name: dist-aarch64-linux
            os: ubuntu-20.04
          - name: dist-x86-64-linux
            os: ubuntu-20.04
          - name: dist-x86-64-msvc
            os: windows-latest
    defaults:
      run:
        shell: "${{ contains(matrix.os, 'windows') && 'msys2' || 'bash' }}"
    steps:
      - name: checkout the source code
        uses: actions/checkout@v4
      - name: run build job
        run: bash ci/run-build.sh
        if: success() && !env.SKIP_JOB
