name: Test Release
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: "Job - ${{ matrix.name }}"
    runs-on: "${{ matrix.os }}"
    env:
      CI_JOB_NAME: "${{ matrix.name }}"
    strategy:
      matrix:
        include:
          - name: dist-aarch64-linux
            env:
              IMAGE: dist-aarch64-linux
              AAAA: 1
            os: ubuntu-20.04
          - name: dist-x86-64-linux
            env:
              IMAGE: dist-x86-64-linux
              AAAA: 1
            os: ubuntu-20.04
          - name: dist-x86-64-msvc
            env:
              SCRIPT: "cargo run --release"
              AAAA: 1
            os: windows-latest
    steps:
      - name: checkout the source code
        uses: actions/checkout@v4
      - name: run build job
        run: bash ci/run.sh
